<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>catch方法</title>
</head>
<body>
    <script>
        const p = new Promise((resolve, reject)=>{
            setTimeout(()=>{
                //设置 p 对象的状态为失败, 并设置失败的值
                reject("出错啦!");
            }, 1000)
        });

        // 分别指明成功和失败后执行的回调
        // p.then(function(value){xxx}, function(reason){
        //     console.error(reason);
        // });

        // 也可以只声明失败后执行的回调
        p.catch(function(reason){
            console.warn(reason);
        });
    </script>
</body>
</html>